context:
  name: r-nemo
  version: 0.0.1 # bump

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  path: ../../..

build:
  number: 0
  noarch: generic

requirements:
  host:
    - r-base
    - r-argparse
    - r-arrow
    - r-assertthat
    - r-dbi
    - r-dplyr
    - r-fs
    - r-glue
    - r-jsonlite
    - r-knitr
    - r-log4r
    - r-purrr
    - r-r6
    - r-readr
    - r-rlang
    - r-rpostgres
    - r-tibble
    - r-tidyr
    - r-ulid
    - r-yaml
  run:
    - r-base
    - r-argparse
    - r-arrow
    - r-assertthat
    - r-dbi
    - r-dplyr
    - r-fs
    - r-glue
    - r-knitr
    - r-log4r
    - r-purrr
    - r-r6
    - r-readr
    - r-rlang
    - r-rpostgres
    - r-tibble
    - r-tidyr
    - r-ulid
    - r-yaml

tests:
  - r:
      libraries:
        - nemo
  - script:
    - nemo.R --version

about:
  homepage: https://github.com/umccr/nemo
  summary: Tidy and explore outputs from bioinformatic pipelines
  description: Provides the building blocks for tidying and exploring outputs from bioinformatic pipelines.
  license: MIT
  license_file: LICENSE
  repository: https://github.com/umccr/nemo
  documentation: https://umccr.github.io/nemo

extra:
  recipe-maintainers:
    - pdiakumis
